# .github/workflows/maven.yml
name: Java CI with Maven

# Déclenche le workflow sur un push ou une pull request vers la branche main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Exécute le job sur la dernière version d'Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code source
      - uses: actions/checkout@v3

      # Étape 2: Configuration de JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Étape 3: Compilation et tests avec Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Étape 4: Archivage des artefacts de build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: calculator-package
          path: target/*.jar